# fly.toml app configuration file generated for openbooklm on 2025-01-20T16:40:22-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openbooklm'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[env]
  HOSTNAME = '0.0.0.0'
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
