apiVersion: apps/v1
kind: Deployment
metadata:
  name: openbooklm
  labels:
    app: openbooklm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openbooklm
  template:
    metadata:
      labels:
        app: openbooklm
    spec:
      containers:
      - name: openbooklm
        image: ghcr.io/open-biz/openbooklm:main  # Updated to use GitHub Container Registry
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: openbooklm-config
        - secretRef:
            name: openbooklm-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
