apiVersion: apps/v1
kind: Deployment
metadata:
  name: openbooklm
  namespace: openbooklm
  labels:
    app: openbooklm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openbooklm
  template:
    metadata:
      labels:
        app: openbooklm
    spec:
      containers:
        # Frontend container
        - name: frontend
          image: node:20-slim
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-credentials
                  key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-credentials
                  key: CLERK_SECRET_KEY
            - name: DATABASE_URL
              value: 'postgresql://postgres:postgres_password@postgres.openbooklm.svc.cluster.local:5432/openbooklm'
            - name: REDIS_URL
              value: 'redis://redis:6379'
            - name: NODE_ENV
              value: 'production'
            - name: NEXT_PUBLIC_API_URL
              value: 'http://172.234.2.105:8000'
            - name: NEXT_PUBLIC_BASE_URL
              value: 'http://143.42.127.58'
          resources:
            requests:
              cpu: '500m'
              memory: '1Gi'
            limits:
              cpu: '1000m'
              memory: '2Gi'
          command: ['/bin/sh', '-c']
          args:
            - |
              set -e
              apt-get update
              apt-get install -y git openssl libssl-dev ca-certificates
              npm install -g pnpm
              git clone -b main https://github.com/open-biz/openbooklm.git 
              cd openbooklm
              pnpm install
              npx prisma generate
              pnpm build
              pnpm start

        # Backend container (single definition)
        - name: backend
          image: python:3.12-slim
          ports:
            - containerPort: 8000
          env:
            - name: CEREBRAS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: CEREBRAS_API_KEY
            - name: LLAMA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: LLAMA_API_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: OPENAI_API_KEY
          # Backend container
          command: ['/bin/sh', '-c']
          args:
            - |
              set -e
              apt-get update
              apt-get install -y git python3-pip python3-venv ffmpeg libsndfile1 libportaudio2
              git clone -b main https://github.com/open-biz/openbooklm.git
              cd openbooklm
              chmod +x setup/create_venv.sh
              ./setup/create_venv.sh
              source venv/bin/activate
              # Run the Groq server
              python3 backend/groq/main.py
          resources:
            requests:
              cpu: '500m'
              memory: '4Gi'
            limits:
              cpu: '1000m'
              memory: '8Gi'
          # Removed readinessProbe and livenessProbe
