apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openbooklm-ingress
  namespace: openbooklm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: '100m' # Allow up to 100MB files
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '600' # 10 minutes connection timeout
    nginx.ingress.kubernetes.io/proxy-send-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/client-max-body-size: '100m' # Also set client max body size
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - openbooklm.com
      secretName: openbooklm-tls
  rules:
    - host: openbooklm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openbooklm-frontend
                port:
                  number: 3000
          - path: /python/
            pathType: Prefix
            backend:
              service:
                name: openbooklm-backend
                port:
                  number: 8000
