apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openbooklm-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - openbooklm.com
    secretName: openbooklm-tls
  rules:
  - host: openbooklm.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openbooklm
            port:
              number: 80
