apiVersion: v1
kind: Secret
metadata:
  name: openbooklm-secrets
type: Opaque
# Note: Values should be base64 encoded in a real deployment
# You'll need to replace these with your actual encoded secrets
data: {}
