apiVersion: v1
kind: Service
metadata:
  name: openbooklm
  namespace: openbooklm
spec:
  selector:
    app: openbooklm
  ports:
    - name: frontend
      port: 3000
      targetPort: 3000
    - name: backend
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: openbooklm-frontend
  namespace: openbooklm
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: openbooklm
    # Add more specific selectors if needed
---
apiVersion: v1
kind: Service
metadata:
  name: openbooklm-backend
  namespace: openbooklm
spec:
  type: ClusterIP  # Changed from LoadBalancer since we're using Ingress
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: openbooklm
    # Add more specific selectors if needed
